settings:
  workers: 5
inputs:
- type: beats
  port: 5048

process:
- filter: json
  params:
    source: "message"
    skip_on_invalid_json: true
  on_success:
  - filter: mutate
    add_field: ["source.env","DENVER"]
- filter: prune
  params:
    allow_list: ["data","type","v","sec","source","timestamp"]
- filter: test
  params:
    condition: "[source.env] == 'qa'"
  on_success:
  - filter: mutate
    params:
      add_field:
      - key: "message"
        value: "I am in QA"
  on_failure:
  - filter: mutate
    params:
      add_field:
      - key: "message"
        value: "I am in DEV"
- filter: mutatev
  params:
    add_field:
    - key: "source.env"
      value: "DENVER"
    - key: "source.version"
      value: "1.0.0"
    - key: "v"
      value: "1.0"

outputs:
- output: stdout
  params:
    codec: json
- output: kafka
  params:
    codec: json
    topic_id: "aircraft_hub"